### ISSUE TITLE
Unify/throw away lmap and rmap

### ISSUE THREAD

**Issue by gusty** [gusty/FSharpPlus#39]
I will start quoting what many bloggers states about Profunctors:

> A Profunctor is just a bifunctor that is contravariant in the first argument and covariant in the second.

So, if I have a type that is both a Contravariant and a Functor (covariant) at the same time, that type is a Profunctor where ``rmap`` is ``map`` and ``lmap`` is ``contramap``.

If so, do we need that duplication?

In principle looks like we can safely throw away the ``LMap`` and ``RMap`` invokables, then we can define ``lmap`` and ``rmap`` as aliases of ``contramap`` and ``map`` respectively.

Or we can go even further and throw away ``lmap`` and ``rmap``.

Also we can shorten ``contramap``to ``cmap`` as they did in Purescript.

Finally (this might be a separate issue but let's include it here) we can argue the same for Bifunctor's ``second`` and ``map``.

Any thoughts?

**Comment by wallymathieu** [comment]
I think it would help as it would reduce the complexity of the API surface of F#+. From what I can see of the code lmap and rmap operators look like just aliases for `contramap` and `map`.

One thing that is also a bit weird is having both the operator `<!>` and `<<|`, but I guess it makes more sense as `|>>` is defined.

**Comment by gusty** [comment]
The ``LMap`` and ``RMap`` Invokables (static functions) were already unified, which lead the operatos as functions aliases.

Currently we have many operator/function aliases but they might make sense:

 - ``map`` ``<!>`` ``<<|`` ``|>>`` The function ``map`` is used typically when generalizing the ``.map`` function, ``<!>`` plays well in applicative expressions, it's also widely adopted in many F# projects. ``|>>`` it's used in pipe forwarding expressions, arguably it's the same as ``|> map`` but it's used in some projects that makes heavy use of operators, like FParsec. ``<<|`` It's there mostly for completeness as it's not commonly used.

- ``lmap`` and ``contramap`` are now the same, but when working with Choice's (or Result) it's easier to think about mapping the left part that thinking about contravariants, then ``rmap`` is the for completeness.

- There are more equivalent functions in the library, I think we can keep a balance between having a lot of them, and reducing them to the minimum.

Finally, let me clarify that this issue is still opened, since it's not 100% clear to me what's the best way to move forward, specially by unifying ``second`` and ``map``. What if we extend the generalization to Tuples, they count from left to right, so second in a 4 element tuple is the the second element, not the third. And if you ask me about Choices of more than two the same reasoning applies to lmap and rmap. This is a consequence that Haskell counts the types right to left because they have partial application of types in their type system which supports higher kinds.

**Comment by wallymathieu** [comment]
Perhaps by adding some of these comments as xml doc ?

**Comment by gusty** [comment]
Definitely which ever direction we go it should be clearly documented.

**Comment by gusty** [comment]
Indeed they do so: http://plantuml.com/pte

**Comment by wallymathieu** [comment]
So I've added a bit of more docs in #80

**Comment by gusty** [comment]
Cool, I have the feeling that these abstractions are more unfamiliar to F-Sharpers so they need probably more docs and examples.

**Comment by gusty** [comment]
It's been a long time thinking about unifying ``second`` and ``map``.

At the moment, my thoughts converge in the direction that there will not be a function ``third``.
Actually ``first`` implies firstOf2 and ``second`` secondOf2.

When dealing with more that 2, we use different names, similarly to the naming in tuples, functions available are only ``fst`` and ``snd`` but for more than that we use ``itemX``, same here. We already have ``ItemX`` and ``MapItemX`` Invokers.

So we can go ahead and unify them, making ``map`` and ``second`` aliases.
