### ISSUE TITLE
PSA: very lightweight HKT Language Suggestion

### ISSUE THREAD

**Issue by robkuz** [gusty/FSharpPlus#46]
Hi,

I just created an [language suggestion](https://github.com/fsharp/fslang-suggestions/issues/566) 
that I think could be interesting for F#Plus.
Maybe some of you want to comment or so

**Comment by gusty** [comment]
Yes, looks interesting and would help type checking, but I wonder how much effort is to implement it, compared with implementing full HKT.

**Comment by robkuz** [comment]
I can not assess how much more or less it might be compared to a full HKT implementation. Thou I somehow expect it to be less complex as there is already a lot of structure checking operators in STRPs.  
But even if I assumed it is the same amount of work to implement either of 2 ... lets be realistic: HKTs wont happen in F#. There is massive resistance to anything that would somehow endanger the total seamless 2-way integration between F# and C# (even thou that seamless integration isn't the case as of today anyways).

So I'd be happy if you could weight in with your support on this.

**Comment by gusty** [comment]
OK. Let's continue the discussion on that thread.
