### ISSUE TITLE
Use the new Result type instead of Choice for Errors

### ISSUE THREAD

**Issue by gusty** [gusty/FSharpPlus#52]
We'll need to adjust to what would be the new standard for signaling errors.

The question is what do we do with the existing type ``Choice<'OK,'Error>``.

I think we should keep if as much as possible for backwards compatibility, but not just between this library version, there might be a lot of source code that uses the Choice convention and needs to keep working without doing a big refactoring.

**Comment by wallymathieu** [comment]
Indeed. 

- You could add a Compatibility namespace with `Choice<'Ok,'Error>`
- You could add a Next namespace with `Result<,>`
- Or go the YoLo path and have both in the same namespace (there might be some things that need to be fixed first though)

**Comment by gusty** [comment]
> Or go the YoLo path and have both in the same namespace (there might be some things that need to be fixed first though)

I decided to use this approach when possible, ie for Functors, Applicatives and Monads. But there are other situations where only one should be the default to model computations.

See my [comment on the commit](https://github.com/gusty/FSharpPlus/commit/d23d847b66ccf593db5d29a90a33dc4d9c12289e#commitcomment-26336555) for a summary of all these changes.

I'm happy to discuss further, are eventually re-open this issue and revert that commit.

**Comment by wallymathieu** [comment]
No, I think selecting one approach is good.
