### ISSUE TITLE
Add Append and Plus for Result

### ISSUE THREAD

**Issue by gusty** [gusty/FSharpPlus#55]
At the moment ``Result`` is not Alternative nor Monoid.

There are many issues with this.

 - Zero and Empty are not always representable.
    In option we have None, but here which is the Zero for Result? It should be ``Error ?`` where ``?`` means in fact no results yet.

 - For Plus and Append there multiple valid instances:
   I'm tempted to add instances consistent with the existing for option. This means "the first good" for Append and "the semigroup of all goods" for Plus, but here there are many possible options for the last case, I mean then Plus between two Errors: take the first, take the second or take both and require that error is a Semigroup.

The last sentence reminds me https://github.com/gusty/FSharpPlus/issues/51 it seems to me that one can argue that error types should be semigroup, to be able to collect validation errors or inner errors.
Strings are semigroups but concatenation of error messages without separators is not a good idea. Maybe there is a way to find a monoid for Exceptions.

**Comment by wallymathieu** [comment]
I've experimented with making tuples instead of only choosing one over the other, however that gives some other weirdness.

**Comment by gusty** [comment]
With tuples, I guess it will not "type check" the expected signatures.

I think we can use a new wrapper type, like ``Validation`` to achieve the other behavior. I mean validations are the opposite, between a Good and a Bad they prefer the Bad and they accumulate the bad ones. So if we go with the ``Plus`` I proposed above, validation will be exactly its dual.

**Comment by gusty** [comment]
I was thinking, if we keep the notion of the Alternative as executing alternatives we can also make ``Async`` an instance of Append. It will run the first async, then do an Async.Catch and then if it fails will run the second.
This could be useful now with the coming redesign of generic Computation Expressions, where the user will have a separate builder for MonadPlus (or Alternative) computations.

Unless there is a more interesting Append for async?

**Comment by gusty** [comment]
I also sympathize with approach 2.
In contrast, here's an explanation of how IO works with what seems to be approach 1: https://stackoverflow.com/questions/48450826/what-is-the-purpose-of-instance-alternative-io

cc: @drvink

**Comment by drvink** [comment]
I would also go with the second approach. I'm familiar with the instance for `Alternative IO` described in the link, though it's never really sat well with me!

**Comment by gusty** [comment]
Deciding over the second option, closing by https://github.com/gusty/FSharpPlus/commit/ce2f8bb5332c687d8c07c942392d29ff74e4a41d
