### ISSUE TITLE
Review/reform toString and tryParse

### ISSUE THREAD

**Issue by gusty** [gusty/FSharpPlus#57]
The difference between ``toString`` and (the F# built-in) ``string`` may be subtle.

I think ``toString`` function can play together with ``tryParse`` in order to get a sort of mini-serializer for simple F# values.

A rule can be enforced, for ``parse`` / ``tryParse``:  ``toString >> parse = id``.

As a consequence, ``toString`` for a ``string`` will add the double quotes and ``tryParse`` will expect them.

The same way ``tryParse`` has a fallback mechanism, ``toString`` (or another function can be created) can fallback to the generic ``string`` function. The idea behind this is that ``toString`` is free of any rule as long as there is no correspondent ``tryParse`` defined for that type.

Here are some examples:

```
toString "abc"
> val it : string = ""abc""

toString ["a"; "b"; "c"]
> val it : string = "[a; b; c]"

toString (set ["a"; "b"; "c"])
> val it : string = "set [a; b; c]"

tryParse<string> "abc"
> val it : string option = None

tryParse<string> ""abc""
> val it : string option = Some "abc"
```

Here's a [relevant discussion in Haskell](https://www.google.com/url?q=https%3A%2F%2Fwww.reddit.com%2Fr%2Fhaskell%2Fcomments%2F2ikmrg%2Fdefine_laws_for_read_and_show%2F&sa=D&sntz=1&usg=AFQjCNHl_nlSJiui9QlQ89PkI-UrU5FIMA) for their read / show functions

Another thing is to consider renaming these functions: ``toString`` might be confused with .NET ``ToString`` instance member and ``parse`` / ``tryParse`` when using any parser library.

Also, if we decide to keep ``toString``, ``parse`` (or maybe ``tryParse``) should be ``fromString``. If we think from the point of view of serializer this makes more sense, but the term string doesn't add any information about the format, it should rather be something like ``toFSharpString`` and ``fromFSharpString`` or shortened as ``toFsString`` / ``fromFsString``.

Finally we can consider keeping the ``parse`` / ``tryParse`` functions and implement a ``fromFsString`` that returns a ``Result`` type, with a detailed parsing error description .... and possibly keep the ``parse`` / ``tryParse`` functions aligned with the ``Parse`` .NET methods, which means language agnostic (?) and no rules at all.

Many open questions.

Please drop your thoughts, specially @mausch who implemented initially the ``ToString`` abstraction. Keep in mind consistency is a high premise of this library.

**Comment by wallymathieu** [comment]
I like the idea!

**Comment by wallymathieu** [comment]
It would be nice to have something like [edn](https://github.com/edn-format/edn) but for f#. Some deviations might be needed, but you could formalize a standard format as a subset of f#.

**Comment by gusty** [comment]
I think the main difference is the strong typing. We can't have heterogeneous lists for instance and instead of symbols we'll have some records with custom printer/parser.

But I see a value on having a printer that output values in an F# format. Sometimes I need to execute something that will output a value and I need to hardcode that value for example in a test. Copy-pasting work only with very basic stuff, but if you have a DateTime, it prints the internal structure whereas it would be useful for this scenario to print the DateTime constructor with all the arguments that will produce that value.

This, of course would not be possible to use with every type, some types can't be re-created by simply applying a constructor + arguments.

Another consequence of this is that a separate generic function can be created for parsing, that uses F# language itself to parse the values.

**Comment by gusty** [comment]
My proposal is:

 -  Parse / TryParse - aligned with .NET methods
 -  ToString - **remove it**, F# has ``string`` which is Culture Independent. So we keep using the instance member ToString, the .NET way.

Then as a side project/enhancement:

 - ToFsString / OfFsString or somethoing like that, which will be an F# values parser / printer.

Since that will be either a side project or an addition, it won't be a breaking change, we can release 1.0 without this.

Any thoughts? @mausch ok to remove ``ToString`` ?
