### ISSUE TITLE
Applicative operators

### ISSUE THREAD

**Issue by gusty** [gusty/FSharpPlus#68]
This decision is in the roadmap to 1.0

We currently have applicative operators which are very convenient to write "formula with effects":

    let x = Some 4 |+| Some 6

    let y = 4 +| tryParse "6"

We can extend this to many other operators, not just basic math:

    |=|
    |>|
    |<|

But when using them with pure values they will become:

``|=``
``|>`` ops, this is the forward pipe
``<|``   ... and this one the backwards

and if we add logic operators:

``|&&|``
``||||`` .. this looks weird.

Maybe we can rename them to:

    .+.
    .-.
    .>.
    .=.
    .||.

Any thoughts?

**Comment by wallymathieu** [comment]
It looks kind of odd with both `.+.` and `|+|`, so I think it's nice that they are in a separate module to avoid some confusion.

**Comment by wallymathieu** [comment]
So I think it makes sort of sense to use `.` if it's possible to have it working with the f# compiler.

**Comment by gusty** [comment]
I'm also inclined towards ``.`` now.

**Comment by ShalokShalom** [comment]
Which characters are possible, next to `.` and `|`?

**Comment by gusty** [comment]
I think all other operator chars are possible to be combined with, in both cases, but the main problem is that combinations with ``|`` yield some existing ones, as I showed.

With ``.`` I'm not aware of many existing operators, apart of the range operators ``..`` and ``.. ..``

**Comment by voronoipotato** [comment]
you might want to consider how this will work with the operator precedence guide  ! % & * + - . / < = > ? @ ^ | ~ . The first character I think is what sets the precedence level. This might affect the utility of the otherwise aesthetic `+.` vs `.+.`

**Comment by voronoipotato** [comment]
actually I was wrong ```
 The operator character . does not affect precedence, so that, for example, if you want to define your own version of multiplication that has the same precedence and associativity as ordinary multiplication, you could create operators such as .*.
```

**Comment by gusty** [comment]
@voronoipotato thats good to know, another good reason for the dots.

**Comment by ShalokShalom** [comment]
So which other operators are open?

**Comment by voronoipotato** [comment]
Well given that we probably don't want operator precedence to break when doing `(A .+. B .+ C)` I do think that the whole "not affecting precedence thing" is going to be a big deal I don't think there's a way to simply disable operator precedence outside of using point-free style. 

``` fsharp
.-.
.+.
./.
.*.
.&&.
.||.
.=.
.<.
.>.
.>=.
.<=.
.%.
.^. //string concatenation
.|>. //piping into a wrapped function int list -> (int -> int) list -> int list, or int option -> (int -> int) option -> int option
.<|. //the other way
.:> // d1Option .:> b1  where d1 is a derived and b1 is the base, and d1 is say inside of a Some type. d1 option -> b1 option. 
.?:> //same
.>>. //composition of two functions. (int -> int) option -> (int -> int) option -> (int -> int) option

```

just some spitballing. Some of these may be bad ideas.

**Comment by gusty** [comment]
> just some spitballing. Some of these may be bad ideas.

Yes, specially function application related, since applicative has it owns, so we don't need them.
 But I found myself in real world scenarios where math related applicatives are very handy.

**Comment by gusty** [comment]
Thanks everybody for your input.
Based on comments and as far as I can tell switching to ``.`` prefix/suffix is the way to go.

Closing as it is already implemented in https://github.com/gusty/FSharpPlus/commit/1a3a5122cced747187e0b5ea8629122bd3202c33
