### ISSUE TITLE
Roadmap to 1.0

### ISSUE THREAD

**Issue by gusty** [gusty/FSharpPlus#71]
I think it's time to draft a roadmap for a stable 1.0 version.

I have always the impression that we're close, but we keep changing stuff in the library.

This is not intended to be a wish list of feature but a list of what are the coming breaking changes we have ahead.

Does anybody wan't to compile a list?

Hint the issues marked as RFCs are all good candidates for the list.

**Comment by ShalokShalom** [comment]
[Is it me?](https://github.com/gusty/FSharpPlus/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+%5BRFC%5D)

**Comment by ShalokShalom** [comment]
Awesome. I post a link to these [RFC](https://github.com/gusty/FSharpPlus/issues?q=is%3Aopen+is%3Aissue+label%3ARFC)`s here and in the F-Sharp Slack channel. 

Hope this helps

**Comment by gusty** [comment]
I think the quotation monad is not a breaking change, so it can be skipped for the roadmap.

**Comment by gusty** [comment]
Filtering out non breaking changes I was able to create the roadmap as a project: https://github.com/gusty/FSharpPlus/projects/1

It seems we're very close.

**Comment by gusty** [comment]
Roadmap was created, wecan close this issue, but feel free to suggest additional items to the roadmap ... and of course PRs and discussions on those individual issues is much appreciated ;)
