### ISSUE TITLE
Namespaces

### ISSUE THREAD

**Issue by gusty** [gusty/FSharpPlus#72]
Given the current (mature) state of the library, it's time to think about the namespaces.

We have currently:

 - FSharpPlus which auto-opens Operators

     - Data: contains all F#+ types, including Monoids, Monads, Collections.
     - Operators contains mostly generic functions and operators that are being added on top of standard F# operators functions, without redefinitions. It also contains some modules:

        - Arrows: defines additional arrow related operators by shadowing bit operators.
        - Applicative Math: although it's in a separated module, these operators don't conflict with anything
        - Generic Math: redefines some very basic math operators, by opening this module you enter in a Generic math mode, it's easier to write generic math functions but some interactions with .net functions with funny semantics for math operators and also units of measures become restricted.

     - Lens: contains not just Lens, it also comes with Prism, Traversals, Iso. I think Optics is being used to encompass all these abstractions. An issue here is that ``set`` is a redefinition of an F# keyword. I was thinking renaming it, maybe to ``burn`` which is the way you cloud write something through a lens in the physical world.

     - Compatibility: At the moment it contains only Haskell, but more modules could be added later for toehr languages (purescript for example). This seems to make sense to me.

 - FsControl contains all (typeclassy) Abstractions, we inherited this namespace from FsControl but we can rename it to either FSharpPlus.Control or FSharpPlus.Invokables, any other suggestion?

Any thoughts?

**Comment by wallymathieu** [comment]
I like `FSharpPlus.Control`. It's short and used in Haskell as well.

**Comment by wallymathieu** [comment]
Perhaps after renaming to `burn` see what part of the diagram from [lens/wiki](https://github.com/ekmett/lens/wiki) is applicable for F#+

**Comment by gusty** [comment]
Yes, we can use plantUML to model the relevant parts of that diagram.

We're open to any other suggestions, apart from ``burn``. If you have other names in mind please shout.

**Comment by wallymathieu** [comment]
Only other name I can come up with is `etch`

**Comment by gusty** [comment]
Another one could be ``setl`` something like *set lens*.

**Comment by wallymathieu** [comment]
True, feels quite Haskelly

**Comment by gusty** [comment]
Done !

**Comment by wallymathieu** [comment]
Nice!

**Comment by gusty** [comment]
This was the last remain (together with the samples folder I removed two days ago) of FsControl.

I feel a bit sad.
