### ISSUE TITLE
Travis build failing

### ISSUE THREAD

**Issue by gusty** [gusty/FSharpPlus#76]
It seems that it's failing in the latest commits with this message:

```
Generating '/home/travis/build/gusty/FSharpPlus/docsrc/tools/../content/abstraction-foldable.html'
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
```

But there's nothing wrong with the build, it works locally and it also succeed in MyGet.

**Comment by wallymathieu** [comment]
It looks like it takes to much time, there are previous builds that have failed in the same way

**Comment by gusty** [comment]
Yes. I was moving lot of code to the docs and to the tests.
Maybe there’s a way to configure it to wait more time.

**Comment by wallymathieu** [comment]
There is, for instance you could split up the build into several travis steps and execute long running doc steps with `travis_wait`. They advise against it (unless you have a good reason for it).

**Comment by voronoipotato** [comment]
You might want to consider caching some of your dependencies. I know mine spends a lot of time just pulling paket files, and i've even had the build fail because it couldn't get a file.  Paket supports local caching as well as networked caching.

**Comment by gusty** [comment]
Thank you both for the advise.
If you could submit a PR that would be much appreciated.
In the meantime, I will keep working doing all the housekeeping with the sample files.
They should either go to the docs or the tests.
Also we should start compiling the docs instead of the samples, but I think we can do that by configuring FSharp Formatting, we also need to make intellisense work in the generated html.

**Comment by wallymathieu** [comment]
I'll see if I can do something. It would be nice to have the build green.

**Comment by wallymathieu** [comment]
It could be an issue on mono. For some reason the thread goes up to 100% on one CPU and does not seem to quit. So using `travis_wait` or caching dependencies will probably not fix this.

**Comment by gusty** [comment]
Weird, what could have caused it?

Trying to track it back, it seems to have appeared around f6fcd131 the only thing I can think is FSharp Formatting in Mono having trouble to render all the docs I moved there.

**Comment by wallymathieu** [comment]
Indeed. I can run the fsx file without problem on mono. I'll see if there is a way to debug FSharp Formatting.

**Comment by wallymathieu** [comment]
If rendering docs works on windows, you could switch to having docs rendered on appveyor and disable it for travis.

**Comment by gusty** [comment]
I'm fine with that. The only downside is that if you want to be maintainer of this library and want to update the docs you'll have to use windows.

**Comment by wallymathieu** [comment]
Indeed. Could be that there is some bug in fsharp formatting.

**Comment by wallymathieu** [comment]
I've tested locally with latest F# formatting beta. Looks like it's able to compile (at least on my machine). I've added a pull request so that we can see how it builds on travis.

**Comment by wallymathieu** [comment]
I'm closing this as the builds are green (according to travis)
