### ISSUE TITLE
Use [<struct>] attribute for DUs

### ISSUE THREAD

**Issue by gusty** [gusty/FSharpPlus#77]
When this project started that was not a possibility, but now in F# 4.1 we can mark DUs as structs and we have many DUs, specially single case (Reader, Cont, ZipList, ... )

At the moment the only value type DU we're using is the recently added Result from FSharp.Core but we should consider adding some more.

I'm looking for a comprehensive guide and recommendations regarding this decision, many of our DU's encapsulates functions, which means that in the end references will be used, some others are more likely to use values, eg NonEmptyList.

This decision is key to stabilize this library, because changing afterwards will break binary compatibility.

**Comment by wallymathieu** [comment]
I usually prefer structs for value types since they are not default nullable in c# ...

**Comment by gusty** [comment]
I'm temped to change everything to struct, but copying (big) struct is more expensive than copying references. So I'm not sure which criteria apply. I've seen lot of discussions regarding performance, specially when struct tuples were proposed, voices promising performance improve, others not really convinced. My impression is that it has to be a case-by-case decision.

**Comment by wallymathieu** [comment]
Indeed, I think there was some GC issues on regular windows .net with using structs over class, so it's not a clearcut choice.

**Comment by wallymathieu** [comment]
So in some cases it can improve perf, and in some cases cause degradation. But it requires a diver from Delos to get to bottom of it.

**Comment by gusty** [comment]
There is a [guideline here](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/choosing-between-class-and-struct)

But if read carefully it states:

AVOID defining a struct unless the type has all of the following characteristics:

 - It logically represents a single value, similar to primitive types (int, double, etc.).

 - It has an instance size under 16 bytes.

 - **It is immutable.**

 - It will not have to be boxed frequently.

So, since DU's are immutable, in theory will show go for structs, or at least not avoid them.

**Comment by wallymathieu** [comment]
Yes, but you still have some annoying behavior around GC. Perhaps something that will be fixed in .net core.

**Comment by gusty** [comment]
Also regarding those guidelines, if this is true for types like ``State`` and ``Writer`` we should also use struct tuples there. Which take us back to #53

**Comment by gusty** [comment]
Closed, for the moment we will use struct DUs for all wrapper types, since they involve wrapping and unwrapping in many basic operations.
