### ISSUE TITLE
Warnings about F# metadata node

### ISSUE THREAD

**Issue by btrepp** [gusty/FSharpPlus#78]
### Description

When compiling a project that references FSharpPlus I get the warning

`unknown(1,1): warning FS3186: An error occurred while reading the F# metadata node at position 878 in table 'ivals' of assembly 'FsControl.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. The node had no matching declaration. Please report this warning. You may need to recompile the F# assembly you are using.`

### Repro steps

Add FSharpPlus to solution
Build

### Expected behavior

No warnings

### Actual behavior

Warnings

Please provide a description of any known workarounds.

### Related information 

* Windows 10
* Nuget installed

**Comment by btrepp** [comment]
Ah looks like theres only really CI tagged builds and nuget didn't install that one. Specifying the CI build number fixed it

**Comment by gusty** [comment]
Oh, I see. You were using the very old 0.xx Nuget.

Yes, that was a very early version, I keep it on Nuget since projects like Fleece still depends on it.

FYI, I will release a new CI today with some breaking changes, specially in the Namespaces.

PS: V1.0 coming soon.

**Comment by gusty** [comment]
Here it is: https://www.nuget.org/packages/FSharpPlus/1.0.0-CI00134
