### ISSUE TITLE
Remove "App.config" from .NET Core build

### ISSUE THREAD

**Issue by irium** [gusty/FSharpPlus#85]
### Description

Now even if my project is pure `netstandard2.0` after installing `1.0.0-CI00148 ` build it got `App.config` included by Paket with all that redirects stuff, that I'm sure not needed at all there.

### Related information 

* Operating system Windows 10 Pro
* .NET SDK :
```
.NET Command Line Tools (2.1.300-preview1-008174)

Product Information:
 Version:            2.1.300-preview1-008174
 Commit SHA-1 hash:  b8df89a54f

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.300-preview1-008174\

Microsoft .NET Core Shared Framework Host

  Version  : 2.1.0-preview1-26216-03
  Build    : f2c3216183d20416568a4bbf5bb7d153e826f153
```

**Comment by wallymathieu** [comment]
So what is the problem?

**Comment by irium** [comment]
At least it clutters Visual Studio and also this `.config` file is going to the `bin` output. And I'm sure it should not be there with all these redirects when my app is `netcoreapp2.0` strict only.

**Comment by wallymathieu** [comment]
And how does you paket file look?

**Comment by irium** [comment]
Now it's like this:

```
framework: auto-detect

source https://www.nuget.org/api/v2

nuget FSharp.Core
nuget FSharpPlus >= 1.0.0-CI00148 content:none
```

Initially, without `content:none` it added config files directly to project (both `fsproj` and folder).
After `content:none` Paket strangely added it as link via `.props` file :

```
  <ItemGroup Condition=" '$(ExcludeRestorePackageImports)' != 'true' ">
    <Content Include="$(NuGetPackageRoot)fsharpplus\1.0.0-CI00148\contentFiles\any\netstandard2.0\App.config" Condition="Exists('$(NuGetPackageRoot)fsharpplus\1.0.0-CI00148\contentFiles\any\netstandard2.0\App.config')">
      <NuGetPackageId>FSharpPlus</NuGetPackageId>
      <NuGetPackageVersion>1.0.0-CI00148</NuGetPackageVersion>
      <NuGetItemType>Content</NuGetItemType>
      <Private>False</Private>
      <Link>App.config</Link>
    </Content>
  </ItemGroup>
```

Maybe there is also a bug in Paket - don't know if this planned behavior of `content:none`.

Anyway, I guess 
```
-    <Content Include="App.config" />
+   <Content Condition=" '$(TargetFramework)' == 'net45'" Include="App.config" />
```
in `FSharpPlus.fsproj` should solve this.

**Comment by wallymathieu** [comment]
So perhaps a pull request with that change?

**Comment by irium** [comment]
I can, but not tested it yet.

**Comment by irium** [comment]
Here it is https://github.com/gusty/FSharpPlus/pull/86

**Comment by wallymathieu** [comment]
Thanks for the contribution! 👍
